In [1]:
from warnings import filterwarnings
filterwarnings("ignore")

# Multiple Linear Regression

In [2]:
import pandas as pd
df=pd.read_csv("D:/Machine-Learning/2.Multiple_Linear_Regression/50_Startups.csv")

In [3]:
df.head()

RND      ADMIN        MKT       STATE     PROFIT
0  165349.20  136897.80  471784.10    New York  192261.83
1  162597.70  151377.59  443898.53  California  191792.06
2  153441.51  101145.55  407934.54     Florida  191050.39
3  144372.41  118671.85  383199.62    New York  182901.99
4  142107.34   91391.77  366168.42     Florida  166187.94

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RND     50 non-null     float64
 1   ADMIN   50 non-null     float64
 2   MKT     50 non-null     float64
 3   STATE   50 non-null     object 
 4   PROFIT  50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [6]:
df.isna().sum()

RND       0
ADMIN     0
MKT       0
STATE     0
PROFIT    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
X= df[["RND","MKT","ADMIN"]]
Y=df[["PROFIT"]]
       
    

In [10]:
X.head()

RND        MKT      ADMIN
0  165349.20  471784.10  136897.80
1  162597.70  443898.53  151377.59
2  153441.51  407934.54  101145.55
3  144372.41  383199.62  118671.85
4  142107.34  366168.42   91391.77

In [11]:
Y.head()

PROFIT
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
model = LinearRegression()
model.fit(X, Y)


LinearRegression()

In [14]:
model.intercept_

array([50122.19298987])

In [15]:
model.coef_

array([[ 0.80571505,  0.02722806, -0.02681597]])

In [16]:
X.columns

Index(['RND', 'MKT', 'ADMIN'], dtype='object')

In [17]:
coefs = pd.Series(model.coef_.flatten(), index=X.columns)
coefs

RND      0.805715
MKT      0.027228
ADMIN   -0.026816
dtype: float64

In [18]:
coefs.plot(kind="bar")

<Axes: >

# VPROFIT = 50122.19 + 0.8057xRND -0.0268xADMIN + 0.0272xMKT

### following conclusion can be drawn

### 1.IF RND increases by 1000 , Profit will increase by 805.7

### 2.IF MKT increases by 1000, Profit will increase by 27.2

### 3.IF ADMIN increase by 1000 , Profit will decrease by 26.8

# Prediction on X

In [19]:
ypred = model.predict(X)
ypred[0:5]

array([[192521.25289008],
       [189156.76823227],
       [182147.2790962 ],
       [173696.70002553],
       [172139.51418327]])

In [20]:
Y.head()

PROFIT
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

# Evaluate the model

In [21]:
from sklearn.metrics import (
    mean_squared_error,
    root_mean_squared_error,
    mean_absolute_error,
    mean_absolute_percentage_error,
    r2_score
)

In [22]:
def evaluate_model(model, x, y):
    ypred = model.predict(x)
    mse = mean_squared_error(y, ypred)
    rmse = root_mean_squared_error(y, ypred)
    mae = mean_absolute_error(y, ypred)
    mape = mean_absolute_percentage_error(y, ypred)
    r2 = r2_score(y, ypred)
    print(f"MSE : {mse:.2f}")
    print(f"RMSE : {rmse:.2f}")
    print(f"MAE : {mae:.2f}")
    print(f"MAPE : {mape:.4f}")
    print(f"R2 Score : {r2:.4f}")

In [23]:
evaluate_model(model,X,Y)

MSE : 78417126.02
RMSE : 8855.34
MAE : 6471.45
MAPE : 0.1060
R2 Score : 0.9507


# Out of Sample Prediction

In [24]:
X.columns

Index(['RND', 'MKT', 'ADMIN'], dtype='object')

In [25]:
X.values[0:5]

array([[165349.2 , 471784.1 , 136897.8 ],
       [162597.7 , 443898.53, 151377.59],
       [153441.51, 407934.54, 101145.55],
       [144372.41, 383199.62, 118671.85],
       [142107.34, 366168.42,  91391.77]])

In [26]:
rnd = 1_00_000
mkt = 1_20_000
admin= 30_000
xnew = [[rnd, mkt,admin]]
model.predict(xnew)

array([[133156.5867057]])

For startups More budget should be allocated to RND for earning more profit